### ISSUE TITLE
Support for Aliyun OSS as a storage backend

### ISSUE THREAD

**Issue by RiKaCC** [livekit/egress#114]

**Comment by davidzhao** [comment]
It should be fairly easy to add, if you are interested in opening a PR for it! It involves:

1. adding a message & field for it [in the protocol](https://github.com/livekit/protocol/blob/main/livekit_egress.proto#L77)
2. create [an uploader](https://github.com/livekit/egress/blob/main/pkg/pipeline/sink/upload.go)

**Comment by tomxiong** [comment]
Hi @davidzhao, I fork a branch to support Aliyun OSS and made some code change with protocol and egress like such you mentioned. Could I take this issue and make a pull request for it.

https://github.com/tomxiong/protocol/commit/699e9043fe5618a229bbdf181849b0f687141211
https://github.com/tomxiong/egress/commit/dd88e37ed91f4f13858e37a21b72e6a86935b889#diff-a3d824da3c42420cd5cbb0a4a2c0e7b5bfddd819652788a0596d195dc6e31fa5

But I also add support Redis cluster too due to my project need. I will open another issue for support Redis cluster.

Thanks.

**Comment by tomxiong** [comment]
hi @RiKaCC ，this feature already implemented. Please try to use it with Alioss and feel free to tell use any issues if you have.
@davidzhao , You can close this issue.
