### ISSUE TITLE
[BUG]Version compatibility issues with the latest version of livekit-server and egress

### ISSUE THREAD

**Issue by keaipeng123** [livekit/egress#578]
Dear author, hello.
When using the latest versions of livekit-server:v1.5.2 and egress:v1.7.5, there is a bug where the egress update fails. However, the bug does not appear on livekit-server:v1.4.3 and egress:v1.7.5.
After testing, egress:v1.7.13 also had this problem. Is the egress of Series 1.7 not compatible with the latest version of livekit?
The following is the error log:
![image](https://github.com/livekit/egress/assets/90554992/621fee77-070c-40c2-9e16-995db7f3a558)
So I tried replacing egress: v1.8.0 to test it, but there was a new problem. The egress closes immediately after startup, and this is where things can go wrong.
![image](https://github.com/livekit/egress/assets/90554992/cfe3f391-06c1-4c7d-9a4a-16e94e854c91)
I hope to have your reply as soon as possible. Thank you very much.

**Comment by keaipeng123** [comment]
![image](https://github.com/livekit/egress/assets/90554992/7afe9828-8f8b-4c56-9ab7-2325e2b5bbc2)
I tried to start this way, there is no problem above, what is the specific reason?

**Comment by rastop123g** [comment]
I encountered a similar problem, as far as I understand, the error failed to launch chrome "websocket url timeout reached" occurs in the library used to launch chrome and in fact has nothing to do directly with the websocket. This is actually a chrome startup timeout. In my case, this was due to the fact that the cloud provider provided a very slow hdd disk and chrome did not have time to load from the disk within the timeout. If you are using a slow hdd, try changing the disk to an ssd, this completely solved my problem, I have never seen such an error again.
ps: it would be nice to be able to load chrome into ram when egress starts
pps: if once you managed to start recording on the egress server, then the error no longer appears on the running instance

**Comment by cagrisungur** [comment]
> I encountered a similar problem, as far as I understand, the error failed to launch chrome "websocket url timeout reached" occurs in the library used to launch chrome and in fact has nothing to do directly with the websocket. This is actually a chrome startup timeout. In my case, this was due to the fact that the cloud provider provided a very slow hdd disk and chrome did not have time to load from the disk within the timeout. If you are using a slow hdd, try changing the disk to an ssd, this completely solved my problem, I have never seen such an error again. ps: it would be nice to be able to load chrome into ram when egress starts pps: if once you managed to start recording on the egress server, then the error no longer appears on the running instance(chrome binaries and libraries cached in ram)

Hello,

Thank you for the information. I'm using an older version of Egress. I designed the project using autoscaling on Azure. However, sometimes, within 1-2 minutes of opening a stream, it starts giving a "websocket url timeout reached" error, and the stream stops.

I couldn't figure out the reason for it. Sometimes I open 4 streams and there are no issues at all. I really can't understand this inconsistent error.

Which version did you experience this issue with? Do you have any other potential problems in mind?

The server is on a machine with 4 cores and 8GB of RAM.

**Comment by rastop123g** [comment]
@cagrisungur I initially ran an egress instance on a local machine with access to redis in the cloud and never got this error, after I moved the instance to the cloud I started getting this error. The configuration was 4gb 4core, and the error appeared constantly when starting the machine. I examined the source code of the place where the error occurred and came to the conclusion that it was a chrome startup timeout; changing the hdd to an ssd from a provider with a high reading speed completely solved the problem on all versions of egress

**Comment by ozgur-d** [comment]
In our case, this problem was solved as follows. We were scaling this server using VMSS. When a duplicate instance is created, we encounter this error, but when we delete the docker image from the instance and download it again, we do not receive any errors. We could not understand the reason, but it seems to be a problem related to copying the same docker image to a different disk. Therefore, we created a VMSS by deleting the docker image. Every time an instance starts, it re-downloads the docker image to that machine. This way, it works smoothly.
